import aiosmtplib
from email.message import EmailMessage


async def send_lead_email(smtp_config: dict, to_email: str, lead_data: dict, project_name: str):
    if not smtp_config or not smtp_config.get('host'):
        print("⚠️ SMTP: Config is missing host")
        return False

    try:
        message = EmailMessage()
        from_addr = str(smtp_config.get('from_email') or smtp_config.get('username') or "")

        message["From"] = from_addr
        message["To"] = str(to_email or "")
        message["Subject"] = f"🚀 New Lead: {project_name}"

        table_rows = ""
        for key, value in lead_data.items():
            label = key.replace('_', ' ').capitalize()
            table_rows += f"""
                <tr>
                    <td style="padding: 12px; border-bottom: 1px solid #edf2f7; color: #718096; font-size: 14px; width: 35%;">{label}</td>
                    <td style="padding: 12px; border-bottom: 1px solid #edf2f7; color: #2d3748; font-size: 14px; font-weight: 600;">{value}</td>
                </tr>
            """

        html_content = f"""
        <html>
        <body style="font-family: 'Segoe UI', sans-serif; line-height: 1.6; padding: 20px;">
            <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); border: 1px solid #e2e8f0;">
                <div style="background-color: #2563eb; padding: 24px; text-align: center;">
                    <h1 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: 700;">TouchCraft</h1>
                    <p style="color: #bfdbfe; margin: 4px 0 0 0; font-size: 14px;">New Message Received</p>
                </div>

                <div style="padding: 32px;">
                    <h2 style="margin-top: 0; color: #1e293b; font-size: 18px; border-left: 4px solid #2563eb; padding-left: 12px;">
                        Website: {project_name}
                    </h2>

                    <p style="color: #4a5568; font-size: 15px;">You have received a new inquiry from your website contact form:</p>

                    <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                        {table_rows}
                    </table>
                    
                    <div style="margin-top: 32px; text-align: center;">
                        <a href="https://touchcraftai.com/leads" 
                           style="background-color: #2563eb; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 10px; font-weight: bold; display: inline-block; box-shadow: 0 4px 12px rgba(37, 99, 235, 0.2);">
                           View All Leads
                        </a>
                    </div>

                    <div style="margin-top: 32px; text-align: center;">
                        <p style="font-size: 12px; color: #a0aec0;">
                            This message was automatically generated by TouchCraft Builder.<br>
                            To manage your leads, visit your dashboard.
                        </p>
                    </div>
                </div>
            </div>
        </body>
        </html>
        """

        text_content = f"New lead from {project_name}:\n" + "\n".join([f"{k}: {v}" for k, v in lead_data.items()])

        message.set_content(text_content)
        message.add_alternative(html_content, subtype="html")

        host = str(smtp_config.get('host', ""))
        port = int(smtp_config.get('port', 587))
        user = str(smtp_config.get('username', ""))
        password = str(smtp_config.get('password', ""))

        is_port_465 = (port == 465)

        await aiosmtplib.send(
            message,
            hostname=host,
            port=port,
            username=user,
            password=password,
            use_tls=is_port_465,
            start_tls=not is_port_465,
            timeout=10
        )
        return True
    except Exception as e:
        print(f"❌ Async SMTP Error: {str(e)}")
        return False
